version: "3.8"

services:
  api:
    restart: always
    build: .
    ports:
      - 5138:80
    volumes:
      - ~/.aws/:/root/.aws:ro
    network_mode: 'host'
    depends_on:
      - "mongo"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    volumes:
      - './data:/data/db'
    ports:
      - '27017:27017'
    network_mode: 'host'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    network_mode: 'host'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: localhost:27017
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_ADMIN_PASSWORD}
